version: '3.7'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VER: ${XNAT_VER}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
    volumes:
      - ./xnat/plugins:/data/xnat/home/plugins
      - ./xnat-data/home/logs:/data/xnat/home/logs
      - ./xnat-data/archive:/data/xnat/archive
      - ./xnat-data/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
      - plugin-download
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=/data/xnat/home
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    build:
      context: ./postgres
      args:
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_ADMIN_PASSWORD}

  xnat-nginx:
    build: ./nginx
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - xnat-web

  plugin-download:
    image: jgoclawski/wget:latest
    volumes:
      - ./xnat/plugins:/plugins
    command: >
      sh -c "wget -nc -q -P /plugins/ https://api.bitbucket.org/2.0/repositories/icrimaginginformatics/ohif-viewer-xnat-plugin/downloads/ohif-viewer-3.0.0-XNAT-1.8.0.jar &&
             wget -nc -q -P /plugins/ https://api.bitbucket.org/2.0/repositories/xnatdev/container-service/downloads/container-service-3.0.0-fat.jar && 
             wget -nc -q -P /plugins/ https://api.bitbucket.org/2.0/repositories/xnatx/xnatx-batch-launch-plugin/downloads/batch-launch-plugin-0.4.0.jar && 
             wget -nc -q -P /plugins/ https://api.bitbucket.org/2.0/repositories/xnatx/ml-plugin/downloads/ml-plugin-1.0.0.jar && 
             wget -nc -q -P /plugins/ https://api.bitbucket.org/2.0/repositories/xnatx/datasets-plugin/downloads/datasets-plugin-1.0.0.jar"
