version: '3.7'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        CI_URL: ${CI_URL}
        XNAT_SITE_URL: ${XNAT_SITE_URL}
        XNAT_VERSION: ${XNAT_VERSION}
        XNAT_SMTP_ENABLED: ${XNAT_SMTP_ENABLED}
        XNAT_SMTP_HOSTNAME: ${XNAT_SMTP_HOSTNAME}
        XNAT_SMTP_PORT: ${XNAT_SMTP_PORT}
        XNAT_SMTP_AUTH: ${XNAT_SMTP_AUTH}
        XNAT_SMTP_USERNAME: ${XNAT_SMTP_USERNAME}
        XNAT_SMTP_PASSWORD: ${XNAT_SMTP_PASSWORD}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
        XNAT_EMAIL: ${XNAT_EMAIL}
    ports:
      - 8104:8104
      - 8080:8080
    volumes:
      - ../xnat-data/home/plugins:${XNAT_HOME}/plugins
      - ../xnat-data/home/logs:${XNAT_HOME}/logs
      - ../xnat-data/archive:${XNAT_ROOT}/archive
      - ../xnat-data/build:${XNAT_ROOT}/build
      - ../xnat-data/cache:${XNAT_ROOT}/cache
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      - XNAT_HOME=${XNAT_HOME}

  xnat-db:
    build:
      context: ./postgres
      args:
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_ADMIN_PASSWORD}

